"""Exhaust GL(4,2) output eigenrow gauges against 124 seven-tail orders.

Every invertible binary linear map on the four output bits is generated by
directed CNOT row permutations. We breadth-first enumerate all 20160 maps.
For each, modular target realignment rank at p=97 is a rigorous lower bound
on exact rank, while a CNOT-factor mincut upper-bounds a seven-CNOT tail of
the tested pair order. If p=97 leaves a candidate, p=193 can refine it.
"""

from collections import Counter, deque
import json
from pathlib import Path

from search13_output_cx_near_tail_rank import EDGES, MASKS, output_cx_rows, target_mod
from search13_rank8_neighborhood_mixedcut import rank_mod, realignment, schedules
from search13_rank8_global_twocut import bond_graph, edge_connectivity_up_to_four


ROOT = Path(__file__).resolve().parent
OUT = ROOT / "search13_all_linear_output_near_tail_rank_result.json"
PRIMES = (97, 193)


def linear_row_permutations():
    identity = tuple(range(16))
    generators = [(edge, output_cx_rows(*edge)) for edge in EDGES]
    seen = {identity: (0, ())}
    queue = deque([identity])
    while queue:
        current = queue.popleft()
        depth, word = seen[current]
        for edge, indices in generators:
            nxt = tuple(current[i] for i in indices)
            if nxt not in seen:
                seen[nxt] = (depth + 1, word + (edge,))
                queue.append(nxt)
    assert len(seen) == 20160
    return seen


def main():
    assert not OUT.exists(), OUT
    gauges = linear_row_permutations()
    near = schedules()
    assert len(near) == 124
    graphs = [bond_graph(s) for s in near]
    capacities = {m: tuple(edge_connectivity_up_to_four(g, m) for g in graphs)
                  for m in MASKS}
    # Prefer masks with the strongest total potential to exclude schedules.
    ordered_masks = sorted(MASKS, key=lambda m: (sum(c >= 4 for c in capacities[m]),
                                               sum(capacities[m]), m))
    bases = {p: target_mod(p) for p in PRIMES}
    hist = Counter()
    tested_masks = Counter()
    rows = []
    for n, (permutation, (depth, word)) in enumerate(gauges.items(), 1):
        possible = set(range(len(near)))
        for prime in PRIMES:
            if not possible:
                break
            target = bases[prime][list(permutation), :]
            for mask in ordered_masks:
                rank = rank_mod(realignment(target, mask), prime)
                tested_masks[prime] += 1
                possible = {i for i in possible
                            if rank <= (1 << capacities[mask][i])}
                if not possible:
                    break
        hist[(depth, len(possible))] += 1
        if possible:
            rows.append({"row_permutation": permutation,
                         "minimum_output_cx_length": depth,
                         "representative_output_cxs": word,
                         "surviving_schedules": [[list(edge) for edge in near[i]]
                                                 for i in sorted(possible)]})
        if n % 2000 == 0:
            print(json.dumps({"gauges_checked": n,
                              "gauges_with_survivors": len(rows)}), flush=True)
    result = {"source": "exact14 eight-CNOT tail with all GL(4,2) output row gauges",
              "primes": PRIMES, "masks": len(MASKS),
              "linear_output_gauges": len(gauges),
              "neighborhood_schedules": len(near),
              "rank_checks_by_prime": dict(tested_masks),
              "survival_histogram_depth_and_count": {f"{d},{s}": c for (d, s), c in sorted(hist.items())},
              "gauges_with_survivors": len(rows),
              "total_survivor_pairs": sum(len(row["surviving_schedules"]) for row in rows),
              "rows_with_survivors": rows,
              "scope": "exhaustive finite linear-output-gauge family and 124 near-tail orders; necessary conditions only"}
    OUT.write_text(json.dumps(result, indent=2, sort_keys=True) + "\n")
    print(json.dumps({"gauges_with_survivors": len(rows),
                      "total_survivor_pairs": result["total_survivor_pairs"],
                      "rank_checks": dict(tested_masks)}), flush=True)


if __name__ == "__main__":
    main()
